# TODO: 补充docker compose配置文件
version: "3"
services:
  app:
    restart: always
    build: .
    command: >
      bash -c
      "python3 manage.py init_db &&
      python3 manage.py runserver &&
      gunicorn -w4 -b :8000 --log-level=debug manage:app"
    container_name: app
    volumes:
      - .:/code
      - static-volume:/code/app/static
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    image: mysql:5.7
    volumes:
      - "/home/ubuntu/mysql:/var/lib/mysql"
    container_name: mysql
    expose:
      - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=2020012425
      - MYSQL_DATABASE=thss
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

    networks:
      - db_network
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000"
    volumes:
      - static-volume:/code/static
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume: